//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public System.DateTime dob { get; set; }
        public int age { get; set; }
        public int branch_Id { get; set; }
        public int class_Id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ProcessedApplication ProcessedApplication { get; set; }
        public string Name { get; internal set; }
    }
}
