//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string category { get; set; }
        public string lst_application { get; set; }
        public int total_by_category { get; set; }
        public int total_no_of_application { get; set; }
    }
}
